import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  const handleClick = () => {
    console.log("button Clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>College Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/col.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Find College's</h1>
        <Banner
          buttonText="view college near me"
          handleOnClick={() => handleClick()}
        />
      </main>
    </div>
  );
}
